

services:
  postgres:
    image: postgres:16
    container_name: url_postgres
    environment:
      POSTGRES_USER: urluser
      POSTGRES_PASSWORD: urlpass
      POSTGRES_DB: urldb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: url_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
